
substitutions:
  devicename: "intergas-xtreme-monitor-esp32"
  friendly_devicename: Intergas Xtreme monitoring (ESP32)

esp32:
  board: nodemcu-32s

# Enable logging
# The ESP32 has 3 UARTs:
# UART0 is used for logging output.
# UART2 is used for communicating to the heater
#
# - We use Tx and Rx from UART2.
# - We use a optocoupler to decouple from feeding back any voltage from the
#   heater into the D8 pin.
uart:
  - id: uart_2
    rx_pin: GPIO17
    tx_pin: GPIO16
    baud_rate: 9600

logger:
  hardware_uart: UART0
  level: DEBUG
  baud_rate : 115200

web_server:
  port: 80

output:
  - platform: ledc
    id: onboard_led
    pin:
      number: GPIO2

# A number of One-Wire sensors can be added to the ESP32.
dallas:
  - pin: GPIO27
    update_interval: 2s

<<: !include intergas-xtreme-monitor-base.include
